
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/03_minibatch_training_OMO.ipynb

from exp.nb_02 import *

import torch.nn.functional as F

#define a function to calculate accuracy of preds
def accuracy(out,yb): return (out.argmax(dim=1)==yb).float().mean()

from torch import optim

class Dataset():
    def __init__(self,x,y): self.x, self.y = x,y
    def __len__(self): return len(self.x)
    def __getitem__(self,i): return self.x[i], self.y[i]

from torch.utils.data import DataLoader, SequentialSampler, RandomSampler

def get_dls(train_ds, valid_ds, bs,**kwargs):
    return DataLoader(train_ds, batch_size=bs,shuffle=True,**kwargs), DataLoader(valid_ds, batch_size=2*bs,shuffle=False,**kwargs)